# Generated by Django 5.2.11 on 2026-03-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitiesQuantities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'entities_quantities',
                'db_table_comment': 'Table of quantities associated to unit entities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitsystemsWdunits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'unitsystems_wdunits',
                'db_table_comment': 'Join table for wdunits and unitsystems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wdclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('isq', models.CharField(blank=True, max_length=128, null=True)),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('section', models.CharField(blank=True, max_length=16, null=True)),
                ('quant', models.CharField(blank=True, max_length=128, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wdclasses',
                'db_table_comment': 'Table of Wikidata Unit Classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wdquants',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('qurl', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('isq', models.CharField(blank=True, max_length=32, null=True)),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('sect', models.CharField(blank=True, max_length=16, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'wdquants',
                'db_table_comment': 'Table of wikidata quantities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WdquantsWdunits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wdquants_wdunits',
                'db_table_comment': 'Join table between wikidata quantities and units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wdsiclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curl', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=32)),
                ('silabel', models.CharField(blank=True, max_length=32, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'wdsiclasses',
                'db_table_comment': 'Table of wikidata SI related classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wdunits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('cls', models.CharField(blank=True, db_column='class', max_length=64, null=True)),
                ('quant', models.CharField(blank=True, max_length=32, null=True)),
                ('factor', models.CharField(blank=True, max_length=256, null=True)),
                ('curl', models.CharField(blank=True, max_length=128, null=True)),
                ('uurl', models.CharField(blank=True, max_length=128, null=True)),
                ('qurl', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=7, null=True)),
                ('found', models.CharField(blank=True, max_length=3, null=True)),
                ('added', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wdunits',
                'db_table_comment': 'Table of unit representations on Wikidata',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='representations',
            options={'managed': False, 'verbose_name_plural': 'representations'},
        ),
        migrations.AlterModelTableComment(
            name='correspondents',
            table_comment='Table of correspondents',
        ),
        migrations.AlterModelTableComment(
            name='dimensions',
            table_comment='Table of dimensions',
        ),
        migrations.AlterModelTableComment(
            name='dimensionvectors',
            table_comment='Table of dimension vectors',
        ),
        migrations.AlterModelTableComment(
            name='domains',
            table_comment='Table of disciplinary domains',
        ),
        migrations.AlterModelTableComment(
            name='encodings',
            table_comment='Table of encodings',
        ),
        migrations.AlterModelTableComment(
            name='entities',
            table_comment='Table of entities',
        ),
        migrations.AlterModelTableComment(
            name='equivalents',
            table_comment='Table of equivalents',
        ),
        migrations.AlterModelTableComment(
            name='factors',
            table_comment='Table of factors',
        ),
        migrations.AlterModelTableComment(
            name='prefixes',
            table_comment='Table of prefixes',
        ),
        migrations.AlterModelTableComment(
            name='quantities',
            table_comment='Table of quantities',
        ),
        migrations.AlterModelTableComment(
            name='quantitykinds',
            table_comment='Table of quantity kinds',
        ),
        migrations.AlterModelTableComment(
            name='quantitykindsunits',
            table_comment='Join table of quantitykinds and units',
        ),
        migrations.AlterModelTableComment(
            name='quantitysystems',
            table_comment='Table of systems of quanitites (e.g. SI)',
        ),
        migrations.AlterModelTableComment(
            name='representations',
            table_comment='Table of unit representations',
        ),
        migrations.AlterModelTableComment(
            name='repsystems',
            table_comment='Table of representation systems',
        ),
        migrations.AlterModelTableComment(
            name='strngs',
            table_comment='Table of text strings',
        ),
        migrations.AlterModelTableComment(
            name='units',
            table_comment='Table of units',
        ),
        migrations.AlterModelTableComment(
            name='unitsystems',
            table_comment='Table of unit systems',
        ),
    ]
