# Generated by Django 4.1.2 on 2022-10-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constants',
        ),
        migrations.AlterModelOptions(
            name='domains',
            options={'managed': False, 'verbose_name_plural': 'domains'},
        ),
        migrations.AlterModelOptions(
            name='repsystems',
            options={'managed': False, 'verbose_name_plural': 'repsystems'},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'managed': False, 'verbose_name_plural': 'units'},
        ),
    ]
