# Generated by Django 4.1.3 on 2022-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_delete_constants_alter_domains_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repsys', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('lang', models.CharField(blank=True, max_length=16, null=True)),
                ('symbol', models.CharField(blank=True, max_length=128, null=True)),
                ('quantity', models.CharField(blank=True, max_length=64, null=True)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('lastupdate', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'entities',
                'managed': False,
            },
        ),
    ]
