# Generated by Django 4.1.3 on 2022-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('name_nist_2018', models.CharField(blank=True, max_length=128, null=True)),
                ('allnames', models.CharField(blank=True, max_length=1024, null=True)),
                ('units_si', models.CharField(blank=True, max_length=64, null=True)),
                ('identifier', models.CharField(blank=True, max_length=128, null=True)),
                ('name_bipm_en', models.CharField(blank=True, max_length=128, null=True)),
                ('name_bipm_fr', models.CharField(blank=True, max_length=128, null=True)),
                ('ucum_constant', models.CharField(blank=True, max_length=32, null=True)),
                ('units_ucum', models.CharField(blank=True, max_length=32, null=True)),
                ('units_uom', models.CharField(blank=True, max_length=128, null=True)),
                ('constant_id', models.CharField(blank=True, max_length=256, null=True)),
                ('is_base', models.CharField(blank=True, max_length=16, null=True)),
                ('qudt_id', models.CharField(blank=True, max_length=256, null=True)),
                ('is_qudt', models.IntegerField(blank=True, null=True)),
                ('is_codata', models.IntegerField(blank=True, null=True)),
                ('is_2018', models.IntegerField(blank=True, null=True)),
                ('is_2014', models.IntegerField(blank=True, null=True)),
                ('is_2010', models.IntegerField(blank=True, null=True)),
                ('is_2006', models.IntegerField(blank=True, null=True)),
                ('is_2002', models.IntegerField(blank=True, null=True)),
                ('is_1998', models.IntegerField(blank=True, null=True)),
                ('vercnt', models.IntegerField(blank=True, null=True)),
                ('nistpage', models.CharField(blank=True, max_length=256, null=True)),
                ('pagetitle', models.CharField(blank=True, max_length=128, null=True)),
                ('symbol', models.CharField(blank=True, max_length=128, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'constants',
                'db_table': 'constants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constantvalues',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('orig_name', models.CharField(blank=True, max_length=128, null=True)),
                ('orig_value', models.CharField(blank=True, max_length=64, null=True)),
                ('orig_uncert', models.CharField(blank=True, max_length=64, null=True)),
                ('orig_unit', models.CharField(blank=True, max_length=64, null=True)),
                ('value_str', models.CharField(blank=True, max_length=32, null=True)),
                ('value_num', models.CharField(blank=True, max_length=32, null=True)),
                ('value_man', models.CharField(blank=True, max_length=16, null=True)),
                ('value_exp', models.IntegerField(blank=True, null=True)),
                ('value_acc', models.PositiveIntegerField(blank=True, null=True)),
                ('uncert_str', models.CharField(blank=True, max_length=128, null=True)),
                ('uncert_num', models.CharField(blank=True, max_length=256, null=True)),
                ('uncert_man', models.CharField(blank=True, max_length=16, null=True)),
                ('uncert_exp', models.IntegerField(blank=True, null=True)),
                ('uncert_acc', models.PositiveIntegerField(blank=True, null=True)),
                ('reluncert_man', models.CharField(blank=True, max_length=8, null=True)),
                ('reluncert_exp', models.IntegerField(blank=True, null=True)),
                ('ellipsis', models.IntegerField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=256, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'constantvalues',
                'managed': False,
            },
        ),
    ]
